# Generated by Django 4.2.3 on 2024-06-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='des',
            field=models.CharField(max_length=200, verbose_name='Enter the Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='head',
            field=models.CharField(max_length=50, verbose_name='Enter the Task '),
        ),
    ]
