# Generated by Django 5.1b1 on 2024-07-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='desc',
            field=models.CharField(default='', max_length=200, verbose_name='Enter the Description'),
        ),
    ]
