# Generated by Django 4.2.3 on 2024-06-25 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_des_alter_task_head'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='des',
            new_name='desc',
        ),
    ]
