# Generated by Django 5.1b1 on 2024-07-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
