# Generated by Django 4.2.3 on 2024-06-27 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_task_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
    ]
